In [1]:
import pandas as pd

In [2]:
df=pd.read_excel("Task.xlsx")

In [3]:
df["total_order"]=df["Order 1"]+df["Order 2"]+df["Order 3"]+df["Order 4"]+df["Order 5"]+df["Order 6"]
df["total_delay"]=df["Delayed Order 1"]+df["Delayed Order 2"]+df["Delayed Order 3"]+df["Delayed Order 4"]+df["Delayed Order 5"]+df["Delayed Order 6"]
df

,Vendor ID,City,Type,Subtype,Rate,Activation Time,Commission Type,Order 1,Order 2,Order 3,...,Delayed Order 6,Delay Rate 1,Delay Rate 2,Delay Rate 3,Delay Rate 4,Delay Rate 5,Delay Rate 6,Training Label,total_order,total_delay
0,1,جویبار,رستوران,فست فود/ایتالیایی,4.171388,2018-11-18 16:18:28,3,138,219,512,...,5,0.021739,0.000000,0.019531,0.027719,0.020619,0.009191,NaN,2545,48
1,4,جویبار,رستوران,فست فود/ایتالیایی,4.183515,2018-11-18 19:10:07,3,778,1707,1298,...,9,0.062982,0.015231,0.015408,0.013270,0.003540,0.003524,NaN,9577,136
2,5,جویبار,رستوران,کترینگ/کبابی,3.988590,2018-11-18 21:02:02,3,45,159,128,...,5,0.000000,0.006289,0.015625,0.014451,0.023810,0.023585,NaN,1016,16
3,6,جویبار,رستوران,رستوران ایرانی,3.930075,2018-11-19 06:20:47,5,49,147,104,...,1,0.122449,0.020408,0.067308,0.006211,0.023810,0.008772,NaN,659,20
4,7,جویبار,رستوران,رستوران ایرانی,4.179931,2018-11-18 17:12:22,3,0,0,0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,4,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,11439,رودبار,رستوران,کافه رستوران,3.862069,2022-01-04 13:20:13,5,0,0,0,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,0,0
7996,11441,رودبار,رستوران,فست فود/ایتالیایی,4.204545,2022-01-03 11:37:58,5,0,21,104,...,15,0.000000,0.047619,0.153846,0.051471,0.148438,0.067873,NaN,610,58
7997,11443,قهستان,رستوران,رستوران ایرانی,4.875000,2022-01-05 21:22:20,5,4,36,82,...,0,0.000000,0.027778,0.036585,0.015075,0.000000,0.000000,NaN,494,7
7998,11445,قائميه,رستوران,رستوران ایرانی,5.000000,2021-12-29 13:11:32,5,4,18,12,...,0,0.000000,0.000000,0.000000,0.032258,0.000000,0.000000,NaN,125,1
7999,11446,داريان,رستوران,فست فود/ایتالیایی,5.000000,2021-12-28 18:03:32,5,1,3,10,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,39,0

In [12]:
df = df[(df['total_order'] > 0)]

df = df[( (df['Order 1']!=0) | (df['Order 2']!=0) | (df['Order 3']!=0 ))]

df

,Vendor ID,City,Type,Subtype,Rate,Activation Time,Commission Type,Order 1,Order 2,Order 3,...,Delayed Order 6,Delay Rate 1,Delay Rate 2,Delay Rate 3,Delay Rate 4,Delay Rate 5,Delay Rate 6,Training Label,total_order,total_delay
0,1,جویبار,رستوران,فست فود/ایتالیایی,4.171388,2018-11-18 16:18:28,3,138,219,512,...,5,0.021739,0.000000,0.019531,0.027719,0.020619,0.009191,NaN,2545,48
1,4,جویبار,رستوران,فست فود/ایتالیایی,4.183515,2018-11-18 19:10:07,3,778,1707,1298,...,9,0.062982,0.015231,0.015408,0.013270,0.003540,0.003524,NaN,9577,136
2,5,جویبار,رستوران,کترینگ/کبابی,3.988590,2018-11-18 21:02:02,3,45,159,128,...,5,0.000000,0.006289,0.015625,0.014451,0.023810,0.023585,NaN,1016,16
3,6,جویبار,رستوران,رستوران ایرانی,3.930075,2018-11-19 06:20:47,5,49,147,104,...,1,0.122449,0.020408,0.067308,0.006211,0.023810,0.008772,NaN,659,20
5,9,جویبار,رستوران,فست فود/ایتالیایی,3.961400,2018-11-19 06:21:02,3,64,102,72,...,0,0.031250,0.009804,0.000000,0.000000,0.000000,0.000000,NaN,510,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7994,11438,رودبار,رستوران,کترینگ/کبابی,4.798319,2021-12-28 15:47:23,5,0,87,150,...,3,0.000000,0.011494,0.020000,0.005208,0.011029,0.006250,NaN,1181,11
7996,11441,رودبار,رستوران,فست فود/ایتالیایی,4.204545,2022-01-03 11:37:58,5,0,21,104,...,15,0.000000,0.047619,0.153846,0.051471,0.148438,0.067873,NaN,610,58
7997,11443,قهستان,رستوران,رستوران ایرانی,4.875000,2022-01-05 21:22:20,5,4,36,82,...,0,0.000000,0.027778,0.036585,0.015075,0.000000,0.000000,NaN,494,7
7998,11445,قائميه,رستوران,رستوران ایرانی,5.000000,2021-12-29 13:11:32,5,4,18,12,...,0,0.000000,0.000000,0.000000,0.032258,0.000000,0.000000,NaN,125,1
7999,11446,داريان,رستوران,فست فود/ایتالیایی,5.000000,2021-12-28 18:03:32,5,1,3,10,...,0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,NaN,39,0

In [14]:
df.to_excel("trained_result.xlsx")